file(READ "${SOURCE_DIR}/main.cpp" SOURCE)
if(SOURCE MATCHES "QIcon::fromTheme")
    message(FATAL_ERROR "Snipping Tool contains an unapproved theme icon lookup")
endif()
foreach(DESKTOP org.aero7.snippingtool.desktop org.aero7.snippingtool-autostart.desktop)
    file(READ "${SOURCE_DIR}/${DESKTOP}" CONTENTS)
    if(NOT CONTENTS MATCHES "Icon=aero7-snipping-tool")
        message(FATAL_ERROR "${DESKTOP} does not use the namespaced launcher icon")
    endif()
endforeach()
if(NOT SOURCE MATCHES "setIconName\\(QStringLiteral\\(\"aero7-snipping-tool\"\\)\\)")
    message(FATAL_ERROR "Notifications do not use the Aero7 Snipping Tool identity")
endif()
