file(GLOB_RECURSE source_files "${SOURCE_DIR}/src/*.cpp" "${SOURCE_DIR}/src/*.h")
foreach(path IN LISTS source_files)
    file(READ "${path}" contents)
    if(contents MATCHES "QIcon::fromTheme")
        message(FATAL_ERROR "Aero7 Gadgets contains a system-theme icon lookup: ${path}")
    endif()
endforeach()
foreach(file org.aero7.GadgetGallery.desktop org.aero7.GadgetHost.desktop org.aero7.GadgetHost-autostart.desktop)
    file(READ "${SOURCE_DIR}/data/${file}" contents)
    if(NOT contents MATCHES "Icon=aero7-gadget-gallery")
        message(FATAL_ERROR "${file} does not use the Aero7 launcher icon")
    endif()
endforeach()
