# Source-order guard; actual portal registration is tested in the Wayland VM.
file(READ "${SOURCE_DIR}/main.cpp" SOURCE)
set(ID "org.aero7.snippingtool")
string(FIND "${SOURCE}" "app.setDesktopFileName(QStringLiteral(\"${ID}\"));" ID_POSITION)
string(FIND "${SOURCE}" "app.setWindowIcon(" ICON_POSITION)
if(ID_POSITION LESS 0 OR ICON_POSITION LESS 0 OR NOT ID_POSITION LESS ICON_POSITION)
    message(FATAL_ERROR "Set the shipped desktop-file ID before GUI resource setup")
endif()
if(NOT EXISTS "${SOURCE_DIR}/${ID}.desktop")
    message(FATAL_ERROR "Application identity has no matching shipped desktop entry")
endif()
file(READ "${SOURCE_DIR}/${ID}.desktop" ENTRY)
if(NOT ENTRY MATCHES "Exec=aero7-snipping-tool --capture")
    message(FATAL_ERROR "Application identity does not resolve to the screenshot launcher")
endif()
